### ISSUE TITLE
How to get the result of test?

### ISSUE THREAD

**Issue by usanyo** [cpputest/cpputest#1013]
Is it possible to get the result of the current test in teardown or somewhere? I would like to save some variable if the test is failed.

**Comment by itavero** [comment]
Since a common guideline for tests is that they should be independent, I am very curious why you would want to do this.

I do not if CppUTest has something built-in for this, but you can always write some value to a shared variable at the end of each test and clear it in the setup.
That way you should be able to see in the teardown if the value has changed or not.

**Comment by usanyo** [comment]
I don't want to violate the independence. I just need a detailed report about my system if a test fails. That's why I need to know if the current test case failed or not. But I've already found the solution. In the setup I set a flag to true, which means I need a report. At the last line of the test I set it to false. I check the flag in teardown. If it is true, I can create the report otherwise no.

**Comment by itavero** [comment]
I can understand why you would want to do that.
On the other hand, for trace-ability, you might just want to add this information to your test reports regardless of the state of the test.

**Comment by basvodde** [comment]
Hi,

You can get the current test via UTest::getCurrentTest() and should get the TestResult from there.

Bas

**Comment by usanyo** [comment]
Hi,

that's what I was looking for.

Thank you!
