### ISSUE TITLE
Windows builds on Appveyor are unreliable

### ISSUE THREAD

**Issue by itavero** [cpputest/cpputest#1016]
While working on PR #1010 I noticed that the Appveyor build is rather unreliable.
It tends to fail because it could not install a dependency (not because the code being verified is wrong).

Check these builds:
- [3.7.0-ci926](https://ci.appveyor.com/project/basvodde/cpputest/build/3.7.0-ci927) with Environment: `Platform=MinGW64, PlatformToolset=5.3.0`
- [3.7.0-ci927](https://ci.appveyor.com/project/basvodde/cpputest/build/3.7.0-ci927) with Environment: `Platform=MinGW32, PlatformToolset=5.3.0`

**Comment by Andne** [comment]
While I'll agree that this behavior is annoying, I don't really know how to fix it.  Currently we suppress all output during install because it was outputting the list of files extracted from the zip file.  A newer version of chocolatey was supposed to clean up that behavior, I haven't checked in a while if that's on appveyor yet.

It may be possible to wrap the install in a try/catch, try to install multiple times in case something unexpected happens the first time.  I'll try to take a look at this when I get a chance.  It's not really ideal, more a workaround than a fix, but may be all we can do.

**Comment by basvodde** [comment]
I think a retry on network error would be exactly what is needed.

**Comment by Andne** [comment]
I added support to the Appveyor build for caching the MinGW installs, hopefully that has cleaned up this issue some.  Looking through the logs it appears that the build hasn't failed due to network errors since.  Any thoughts on closing this?

**Comment by basvodde** [comment]
I remember it failing once, but it seems more stable.
