### ISSUE TITLE
Can I mock classes with non virtual methods?

### ISSUE THREAD

**Issue by ruipacheco** [cpputest/cpputest#1049]
I can't find any reference to this but I'd like to mock a class with non virtual methods, like GoogleMock does: https://github.com/google/googletest/blob/master/googlemock/docs/v1_7/CookBook.md#mocking-nonvirtual-methods

Is this possible? If so, can you point to the documentation?

**Comment by cuitoldfish** [comment]
I think you can define a mock class with same name, same public member function of the target class, but in those member function, mock is used instead of the real implementation.

in a word, let the test program link the mock class to insulate the dependency.

does this solution solve your problem?

**Comment by ruipacheco** [comment]
How do you make my program load the mock class instead of the original one?

Lets assume I want to mock a library I have no control over. How do I do that?

**Comment by uecasm** [comment]
1. #include anything that the library header or the class under test includes and that you don't want to mock (relying on #pragma once and equivalents to prevent later re-includes).
2. open an anonymous `namespace {}` block.  (You can used a named namespace instead, but then you have to remember to use a different name for each test.)
3. inside that block, #include the class header that you want to mock, *and* provide implementation (or reimplement the class to be mocked without including it -- this might be necessary if the header contains inline implementation).  Note that you can write the mock in a separate file and just #include it here (still inside the block), which is handy if you want to mock the same class in many tests.
4. also inside the block, #include the cpp of the class under test (that uses the mock).
5. outside the block but in the same cpp file, implement the tests.

Because of the way that namespaces work, the class under test will bind to the mock implementation rather than the "real" one, even if both are linked in the same executable (just don't put both in the same translation unit).

This doesn't work in all cases -- there are certain constructs that will give you grief, and you'll get a lot of weird errors if you forget a #include -- but it's a great way to be able to mock A in one test (while testing B) but test the real A in another, all in the same executable.

Another option that also works (but has different caveats) is to use templates, so you can supply the real implementation class for the production code and a mock implementation for the tests.  Yet another option is to write a delegating proxy interface class that does have virtual methods.

**Comment by cuitoldfish** [comment]
@ruipacheco, you can use makefile or  linker option to chose whether the real library or the mock library is linked, can't you?

**Comment by ruipacheco** [comment]
@uecasm - Your solution would work without cpputest no?

**Comment by uecasm** [comment]
@ruipacheco If you had a different mocking library to call, sure.  What's your point?

**Comment by ruipacheco** [comment]
I didn't see any specific references cpputest there so I wondered.

Thanks for all the answers!

**Comment by ruipacheco** [comment]
How would this be done? Do you have any examples?
