### ISSUE TITLE
CppUMock calling real function instead of mock function

### ISSUE THREAD

**Issue by mldmelissa** [cpputest/cpputest#1054]
I have an embedded static library that I am attempting to write meaningful unit tests for using CppUTest. I am trying to create mocks in my unit test program for some of the function calls in the static library, without having the actual function in the library being called. For example, I have a function that is called that sends passes data stored in memory to a UART in my library. I want to write a mock for that function call in my unit test that makes sure the correct parameters are being passed at the time of that function call so that the correct memory bytes are being sent through the UART. My problem is occurring when I want my unit test to use the mock function rather than the actual implementation of the function in my static library. 

I use mock().expectOneCall("function_name").withParameter("parameter1",p1) in my TEST(). Then I created a function in my unit test program that is structured as below:

void function_name(int parameter)
{
mock().expectOneCall("function_name").withParameter("parameter1",p1);
}

When i run my unit test, it still ends up jumping to the actual implementation of function_name(), instead of the mocked one in my unit test. Is there a way to use the linker to swap out the real function calls with the mocked ones for CppUMock?

**Comment by Andne** [comment]
The easiest way is just to not link against the library that contains the real versions of the  functions you are mocking.  If the only source of those functions are the mock versions, then they'll get used instead.  This can get a bit complicated if the mocked functions and the tested functions are in the same library, so hopefully that isn't the case.

Depending on project structure, is may be helpful to have multiple static libraries for different layers in the application (i.e. BSP vs application features) and link them together in a final application project to generate your normal executable.  This can make it easier to mock out BSP functions when testing middleware since you don't need to link against the BSP at all until the final application project, so the only version available is the mock.

**Comment by wiredsource** [comment]
did you use: _virtual void function_name(int parameter)_ in your interface?

**Comment by jwgrenning** [comment]
Are you putting the mock version in a library too?

In your unit test build, include the compiled mocks' o files directly, 
and the build must see your mock `function_name()` before the real 
`function_name()`.

thank you, James


--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by jwgrenning** [comment]
Also, are you using `extern "C"`?  Maybe the linker is not seeing your 
function if it is being compiled as a C++ function.

```
//your mock file.cpp
extern "C" {
#include "file_containing_function_name_declaration.h"
}

void function_name(int parameter)
{
	mock().expectOneCall("function_name").withParameter("parameter1",p1);
}
```

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by basvodde** [comment]
I assume this has been resolved by now? If not, please let me know.
