### ISSUE TITLE
"Placement new" conflicts with MemoryLeakDetectorNewMacros.h

### ISSUE THREAD

**Issue by leventesen** [cpputest/cpputest#1114]
There is a sample code at http://www.sourcetricks.com/2008/05/c-placement-new.html
It conflicts with MemoryLeakDetectorNewMacros.h
Error is in line:  #define new new(__FILE__, __LINE__)

**Comment by Andne** [comment]
The documentation located here can help with this: http://cpputest.github.io/manual.html#memory_leak_detection

Look at the sections about conflicts with STL or your own macros, similar action needs to be taken in order to correct this for placement new.  In my code I tend to just `#undef new` at the top of any file containing placement new (I don't use it a lot but sometimes need to), but better solutions may exist as well.
