### ISSUE TITLE
Create Conan package and publish to Conan Center

### ISSUE THREAD

**Issue by shreyasbharath** [cpputest/cpputest#1115]
Conan is a C/C++ package manager. It is to C/C++ what RubyGems/Bundler is to Ruby.

It would be great if a package recipe was created for CppUTest and then published to Conan centre for consumption by other projects.

**Comment by kkass** [comment]
I have not tested it, but I found this. https://bintray.com/covi/ConnectedVision/CppUTest%3Acovi#

**Comment by ZaMaZaN4iK** [comment]
Is this package well-maintained?

**Comment by matlo607** [comment]
Hello,

[https://bintray.com/covi/ConnectedVision/CppUTest%3Acovi#](https://bintray.com/covi/ConnectedVision/CppUTest%3Acovi#) seems not to be maintained anymore.

I recently created a recipe for CppUTest working fine with Conan 1.6.0
```python
from os import path
from conans import ConanFile, CMake


class CppUTest(ConanFile):
    name = "CppUTest"
    version = "3.8"
    description = """C /C++ based unit xUnit test framework for unit testing and for test-driving your code"""
    license = "BSD 3-clause \"New\" or \"Revised\" License, https://github.com/cpputest/cpputest/blob/master/COPYING"
    url = "https://cpputest.github.io"
    settings = "os", "compiler", "arch", "build_type"
    source_dir = "{name}-{version}".format(name=name, version=version)
    options = {
        "shared": [True, False],
        "include_pdbs": [True, False],
        "fPIC": [True, False],
        "tests": [True, False],
        "extensions": [True, False]
    }
    default_options = (
        "shared=False",
        "include_pdbs=False",
        "fPIC=False",
        "tests=False",
        "extensions=True"
    )
    scm = {
        "type": "git",
        "subfolder": source_dir,
        "url": "https://github.com/cpputest/cpputest.git",
        "revision": "tags/v{version}".format(version=version)
    }

    def source(self):
        pass

    def build(self):
        cmake = CMake(self)
        #cmake.verbose = True
        cmake.definitions["TESTS"] = self.options.tests
        cmake.configure(source_dir=path.join(self.source_folder, self.source_dir))
        cmake.build()
        if self.options.tests:
            cmake.test()
        cmake.install()

    def package(self):
        pass

    def package_info(self):
        self.cpp_info.libs = ["CppUTest"]
        if self.options.extensions:
            self.cpp_info.libs.append("CppUTestExt")
        if self.settings.compiler == "Visual Studio":
            self.cpp_info.libs.append("winmm.lib")
```
The test_package is still missing and the recipe not perfect but it is a beginning.
Would you mind creating a new git repository named `conan-cpputest` under `cpputest` hosting the above `conanfile.py` ?

**Comment by offa** [comment]
> Would you mind creating a new git repository named conan-cpputest under cpputest hosting the above conanfile.py ?

Wouldn't it be reasonable to place the `conanfile.py` directly in this repository, or is this bad practice?

I'm looking forward for up-to-date conan releases 👍 .

**Comment by matlo607** [comment]
Actually there are 2 strategies described in the documentation, each with its pros and cons:
* [Recipe and sources in a different repo](https://docs.conan.io/en/latest/creating_packages/external_repo.html)
* [Recipe and sources in the same repo](https://docs.conan.io/en/latest/creating_packages/package_repo.html)

If you use the first approach, it allows to maintain a compatibility between the last release of Conan and an old release of your project. Today, this is how it's done for Boost (https://github.com/conan-community/conan-boost --> [network](https://github.com/conan-community/conan-boost/network)).
Now you can ask, why don't we do this for CMake or autotools ? I would answer CMake is older and more stable. It has kept a retrocompatibility for several years now, while Conan is a young product with a quick release cycle. They privilege new features even if it means breaking recipes written for previous versions. This is not true for 7 months now, since release 1.0.0, 10 January 2018. This [changelog](https://docs.conan.io/en/latest/changelog.html) can give you more insight into the frequency of releases.

With the second approach, you just tell the end user that he will need such version of CMake, such version of the compiler and such version of Conan to build the project at version N. If in 10 years, somebody want to build your project again at version N, he will have to read the README and install the required tools at the appropriate version.

I don't know if putting conanfile.py in a different repository is the best approach. Both of them are equally defendable. It's up to the maintainer to take a decision ;-)

**Comment by offa** [comment]
Woah, thanks for that detailed answer!

The boost conan repo really contains many different versions (funnily enough, most of them fail the CI).

So using an external repo is also the best approach to ship different versions of this library (eg. release 3.8, 3.9, 4.0 and some sort of 'latest'), correct?

**Comment by matlo607** [comment]
> So using an external repo is also the best approach to ship different versions of this library (eg. release 3.8, 3.9, 4.0 and some sort of 'latest'), correct?
I would advise so if you want to be able to use the latest version of Conan.

**Comment by bryceschober** [comment]
I got crickets, so I went ahead and did it myself: https://gitlab.com/bryceschober/conan-cpputest.

This recipe is based on the one from @matlo607, but has some critical fixes and differences:
1. I set it up to build latest master, since 3.8 is so old
1. I used the https://github.com/conan-io/conan-package-tools for boot-strapping public open-source continuous integration
1. It exports the conan build flags to CppUTest, as was necessary for 32-bit builds
1. It includes a basic package test

I started it on GitLab, since it has built-in CI that *just works*.

Things I haven't yet done include:
- [ ] Think about the best way to provide 3.8 vs. master vs. some-other-kind-of-reasonably-stable builds
- [ ] Hooking up accounts to Travis for OSX and AppVeyor for Windows builds:
    Help is wanted here for anyone with accounts / experience about best practices.
- [ ] Hooking up to a bintray account to upload and store packages:
    Help is wanted here for anyone with accounts / experience about best practices.
- [ ] Adding CI status badges to the README.md

**Comment by offa** [comment]
This should become available on [conan center](https://bintray.com/conan/conan-center) somehow.

**Comment by bryceschober** [comment]
Update: 

I've moved the conan-cpputest repo to github (probably better for collaboration with this project), and opened an [issue for the initial MVP](bryceschober/conan-cpputest/issues/1). I intend to move this discussion there.

Please feel free to join the conversation there, contribute PRs, or even volunteer to take over the project. I'm a complete newbie when it comes to both conan and cmake, and am probably not the best one to drive this toward awesomeness... I just happen to be the one that has publicly picked up the baton.

**Comment by offa** [comment]
The link is broken.

**Comment by bryceschober** [comment]
OK, I fixed the link. GitLab is currently just a pull mirror, so contributions should go to GitHub... but I'm not super happy with that, since it doesn't result in GitLab builds from GitHub PRs... so if you have any suggestions, I'm all ears.

**Comment by basvodde** [comment]
Thanks.

I created a new repository at https://github.com/cpputest/conan-cpputest. Feel free to move it there or to change the README to point to your repository.

**Comment by bryceschober** [comment]
@basvodde Does that mean you'll give me admin on that project for the moment?

Actually, the best way forward is probably this:

1. Delete the new cpputest/conan-cpputest project that you just created.
1. Temporarily give me add-project rights to the cpputest organization
1. Then I can transfer the whole existing bryceschober/conan-cpputest repo over to the cpputest org, issues, and all.
1. Then you can remove my organizational-level rights and demote me to a mere maintainer on the transferred cpputest/conan-cpputest project.

Sound good?

**Comment by basvodde** [comment]
Step #1 done. I added you as member. I'm not sure you need rights for transfering your project, I suggest to give it a try.

**Comment by bryceschober** [comment]
@basvodde I just tried step 3 and was given the message "You don’t have the permission to create repositories on cpputest". Looks like I will need repository creation rights, temporarily. If you would like to jump on a more real-time communications medium to minimize the hand-over time, you can reach me on google hangouts at bryce dot schober at gmail dot com or text me at (US) two zero six two two seven zero niner two fiver, or any other method of your choosing.

**Comment by basvodde** [comment]
Ok, try now!

**Comment by bryceschober** [comment]
OK, I'm done migrating bryceschober/conan-cpputest to cpputest/conan-cpputest, so you can demote me from organization-level permissions. I will still need maintainer-level permissions on the conan-cpputest project, unless you want to take over that level of management.

**Comment by basvodde** [comment]
Done. Seems you have write permission now also. Let me know if there is anything else I can do.

And welcome :)

**Comment by claremacrae** [comment]
A note for anyone coming here via search: CppUTest is now in Conan-center:

https://conan.io/center/cpputest

**Comment by offa** [comment]
Great news! :smile:
