### ISSUE TITLE
mingw and pthread.h

### ISSUE THREAD

**Issue by pozzugno** [cpputest/cpputest#1191]
Unfortunately, mingw is considered gcc. During compilation the file src\Platforms\Gcc\UtestPlatform.cpp is used. This file uses pthread.h that mingw can't be find.

I changed the functions PThreadMutexCreate(), PThreadMutexLock(), PThreadMutexUnlock() and PThreadMutexDestroy() with the content of src\Platforms\VisualCpp\UtestPlatform.cpp. I also included <windows.h> instead of <pthread.h>.

In this way I was able to compile libCppUTest.a and libCppUTestExt.a libraries and they seem work well.

I think it would be better to create a new platform, named mingw, different from gcc.

**Comment by Shepdog87** [comment]
Thank you for posting the issue you ran into and your resolution.  I just ran into the exact same thing as you.

**Comment by lemtronix** [comment]
@pozzugno I had the same issue as you, but instead of modifying the UtestPlatform file, I found out that I did not install pthreads from the MinGW installer.  

The package I needed to install was "mingw32-libpthreadgc-dev" from the mingw-get-setup.exe installer.

![ScreenClip](https://user-images.githubusercontent.com/4982321/68141302-dc1dec00-fef2-11e9-8f66-d10ea0f8af6a.png)

Once I installed this package, then I was able to run CMAKE and compile using GCC-8.2.0.

**Comment by Flashzgh** [comment]
hello, i have work it out the problem of pthread.h that mingw can't be find following the tutorial of @pozzugno,but i am meeting the new problem.when i run  the command-->  C:\Users\flash\Desktop\cpputest-3.8\cpputest_build>mingw32-make     
there are the follow errors displaing in the cmd.exe :
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
tests\CMakeFiles\CppUTestTests.dir\build.make:626: recipe for target 'tests/CppUTestTests.exe' failed.
Please help me。

**Comment by basvodde** [comment]
It seems you need to install the pthreads library in your mingw ?
