### ISSUE TITLE
With -p set, test cases that take unusual exit (sanitizers) are counted as success

### ISSUE THREAD

**Issue by alameth** [cpputest/cpputest#1211]
Function `GccPlatformSpecificRunTestInASeperateProcess()` relies on tunnelling `result->getFailureCount()` into the child process and back out through the exit status code. However, a test case failure that takes its own `_exit()` (e.g., a Sanitizer error or other non-signal runtime error) will confuse the logic for counting the number of failures.

My fix is to change the parent/child logic to a simple zero/non-zero check: if the child process returns non-zero, then the test failed; if it returns 0, the test passed. (This means preserving the value of `result->getFailureCount()` across the call to `runOneTestInCurrentProcess()`.)

Happy to submit a pull request if you like.

**Comment by vpod** [comment]
@basvodde : what do you think about it?
While working on https://github.com/cpputest/cpputest/issues/1262 I found a bug in the same function as the code for "debugger support" (w==-1) was failing due to check of initialized "status". As I'm fixing the bug (or my change fails tests), I can fix this issue as well. Especially as I'm reaching the point in my coding where I will finally start returning something for 0 run tests and thus 0 failed tests (which should not happen for child tests, but who knows).

**Comment by vpod** [comment]
Please assign to me
