### ISSUE TITLE
Use of protected members to share data between test fixture and test case

### ISSUE THREAD

**Issue by free-easy** [cpputest/cpputest#1224]
Is the following code valid?

```cpp
TEST_GROUP (mygroup) {
	void setup() {
		// do something with this->member
	}
	void teardown() {
		// do something with this->member
	}

  protected:
	int member;
};

TEST (mygroup, my_test) {
	// do something with this->member
}

```

I've tried and it works, but I want to ask you whether I'm relying on the implementation of the test framework or it's an intended feature.

**Comment by offa** [comment]
This is valid. The generated class for the test public inherits from the generated test group class.

See [here](https://github.com/cpputest/cpputest/blob/9be6d3d528bcb60b728c971b3ccf427174729f65/include/CppUTest/UtestMacros.h#L58) for their macro definitions.

**Comment by free-easy** [comment]
Thank you for the quick reply!

The only problem now is that this feature seems not to be documented anywhere. 
OTOH, I admit that it's something that is quite easy to understand and verify. But, like every project, everything that is undocumented is subject to change. This is the part that worries me.

**Comment by free-easy** [comment]
Thank you for the quick reply!

The only problem now is that this feature seems not to be documented anywhere. 
OTOH, I admit that it's something that is quite easy to understand and verify. But, like every project, everything that is undocumented is subject to change. This is the part that worries me.

**Comment by basvodde** [comment]
It is not likely to ever change.. but you aren't getting a lot of benefits declaring things protected :)

**Comment by free-easy** [comment]
Thank you for the clarification!

**Comment by jwgrenning** [comment]
Hi

It's not a great idea IMO.  If you need access to the private/protected 
parts of a class during test or otherwise, it is likely a design 
problem.  It might be something to do with legacy code while you are 
getting it under test.

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)
