### ISSUE TITLE
Issue compiling using cppUTest with other libraries includes

### ISSUE THREAD

**Issue by cesarberci** [cpputest/cpputest#1233]
I can't compile a C++ test program when include some headers. For example, a have a working test program and, when I introduces:

#include <future>

or

#include "rapdjason/document.h"

The program return many compilation errors.

All sources are compiling and running, include some ones using , the problem is that I can't create unit tests for my source.

I'm crosscompiling a C++ program to Raspbian using Eclipse CDT in a Windows 10.

Example of errors (using <future>)

future:242:11: error: '_M_storage' does not name a type
future:242:21: error: expected ')' before '.' token
future:249:11: error: '_M_storage' does not name a type
future:249:21: error: expected ')' before '.' token
future:284:29: error: expected type-specifier before '(' token
future:284:29: error: expected ')' before '(' token
future:284:30: error: expected primary-expression before 'void'

**Comment by jwgrenning** [comment]
I am not familiar with M_storage.  I suspect it is some non-standard 
annotation needed for RPi.

You might add this macro before that include file to see if that is the 
problem

```
#define _M_storage(x)
```

If that works, you'll want a forced include to do that rather than 
cluttering up your code.  This article might help

[Hiding Non-standard C Keywords for Off-Target 
Testing](http://blog.wingman-sw.com/archives/249).

HTH James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by cxw42** [comment]
Try putting the `#include` statements for cpputest _after_ all your other `#include` statements.  That worked for me!

**Maintainers:** https://cpputest.github.io/manual.html#conflicts-with-operator-new-macros-stl mentions this idea.  Would you be willing to update the manual to recommend this as a general practice, not just for `operator new` conflicts?  I had the same problem as https://stackoverflow.com/q/54611227/2877364 , and was able to solve it by moving the cpputest includes last.  Thanks for considering this request!

**Comment by jwgrenning** [comment]
Hi Chris,

I added a note before MFC conflicts:

----
### Other conflicts in the test file only

If your conflict is only in the test code files, put the CppUTest  
includes after your includes.  Because of this potential conflict, its a 
good idea to put the CppUTest includes after your includes as a 
preemptive measure.
----

Will that help? I am open to suggestions.

I submitted a pull request along with some other stuff.  Hopefully Bas 
will get to it soon.

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by cxw42** [comment]
Looks good to me!
