### ISSUE TITLE
std::null_ptr breaking my clang build

### ISSUE THREAD

**Issue by mayl** [cpputest/cpputest#1248]
Hi,

I've been using CppUTest for a while, and have several test suites.  I use both Clang and GCC.  Recently, I updated to master from this repository and my Clang tests now don't compile.  I get a "fatal error: Unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?" on line 235 of SimpleString.h.  Modifying the header to use std::nullptr_t fixes the issue.

It seems like this is a change that was introduced only a few weeks ago.  Are there any pointers for how to go about fixing my build so I can work off of master CppUTest again?  I'm using the default clang toolchain installed via apt on Ubuntu Xenial. 

Thank You!

**Comment by basvodde** [comment]
Hmmm... that is interesting. We fixed the usage of nullptr_t so that is also works better with other compilers. CLang is included in the CI build, so I'm surprised that it breaks for you. My guess is that it is then wrong in an older (or newer?) clang version. That doesn't help you a lot though.

It probably can be fixed though we'll end up using a hack for this. An easier fix would be to add "using std;" before the #include. Would that be good enough or do you think this is common enough to warrant a more hack-ish fix?

**Comment by selsiddharthsingh** [comment]
Mingw64 also gives the same error. The issue is mentioned in #1232 but then kinda overlooked due to other issue. The fix in #1234 fixes it for ghs and similar compiler but actually breaks it for other compilers. If we revert these changes it will break green-hills compiler and few others which don't put nullptr in std namespace in their library implementation.

This is a messy issue as some libraries define nullptr_t in stddef.h and then include it inside cstddef within the namespace std, others do not. Some like arm or mingw implementation define it in c++config.h and not at all in stddef.h. I am sure if we remove the ```!defined __arm__``` check for this function it will break due to same reasons in arm as it is in mingw. I haven't check the Clang library but I am guessing they have same issue.

Technically, [C standards](https://en.cppreference.com/w/c/types) doesn't mention nullptr_t so I am not sure why these compilers have implementation in C library. This is a C++11 concept and should be in the C++ library like cstddef. But we have to work with what we have.

Now, I can't think of a good way to solve this, I haven't looked much on how ```StringFrom(const nullptr_t value)``` is used but a couple of solutions can be either to get rid of this function (which @basvodde mentions in [issue 1232](https://github.com/cpputest/cpputest/issues/1232#issuecomment-523711062)) or to put it under something like ```#ifdef USE_NULLPTR_T``` check. Just some ideas....

**Comment by mayl** [comment]
Hi Bas,

Thanks for your reply.  I did see that you run a clang build as part of your CI, I agree it's very curious that it doesn't work for me even though those builds pass.  So far, I have only been able to try with clang-6 and clang-8, and it looks like your CI server is using clang-7.  I'm going to try to get clang-7 installed so I can attempt with that soon, but since the issue exists for both the previous and following versions I don't hold out much hope.

I wasn't able to get your "`using std;` before the `# include`" recommendation to work, but I am much more familiar with C than CPP.  Can you be more explicit about what you're proposing?  Do I add `using std;` before the `CppUTest` includes in my test files, or in the system header file?

**Comment by basvodde** [comment]
I like the USE_NULLPTR_T but it won't solve the problem as the problem relates to whether it is in std namespace or not.

I guess we'll need to revert back to add the namespace std:: there and change to include both the stddef and the cstddef in StandardC. Perhaps that would also resolve the other problem. Feel free to try out some pull requests.

**Comment by watersne** [comment]
I am encountering the same issue trying to build the IAR platform using IAR EWARM 8.10.1.

**Comment by offa** [comment]
Is replacing `(std::)nullptr_t` with direct `decltype(nullptr)` an option?

**Comment by basvodde** [comment]
Not sure, but the std:: is back for now. Let's see what problems it'll cause :)

**Comment by offa** [comment]
This is solved by #1264 and #1261, isn't it?
