### ISSUE TITLE
warning: the address of '...' will never be NULL [-Waddress]

### ISSUE THREAD

**Issue by engsergiosoares** [cpputest/cpputest#1395]
Hi guys,

Thanks for the amazing work with cpputest.
When trying to CHECK function pointers, I get a warning. I'm probably doing something wrong but I couldn't really figure out.

Here's my example:

```cpp
#include "CppUTest/TestHarness.h"

TEST_GROUP(false_warning_tests)
{

};

int function1(int a)
{
	return 0;
}

//Warning
TEST(false_warning_tests, function_pointer_no_variable)
{
	int (*func_ptr)(int);
	func_ptr = function1;
	CHECK_EQUAL(function1, func_ptr);
}

//No warning
TEST(false_warning_tests, function_pointer_with_variable)
{
	int (*func_ptr)(int);
	int (*expected_func_ptr)(int);
	func_ptr = function1;
	expected_func_ptr = function1;
	CHECK_EQUAL(expected_func_ptr, func_ptr);
}
```

The warning I get is:
"CppUTest/UtestMacros.h:138:71: warning: the address of 'int function1(int)' will never be NULL [-Waddress]"

Any ideas? Or is this an issue?
Thanks!

**Comment by basvodde** [comment]
Is this with the trunk version. Can you share your line in Macro CppUTest/UTestMacros.h:138:71 ?

**Comment by engsergiosoares** [comment]
Yes, I'm on the master branch, cloned a few days ago.

This is what I have on line 138:
```
UtestShell::getCurrent()->assertEquals(true, StringFrom(expected).asCharString(), StringFrom(actual).asCharString(), text, file, line); \
```

**Comment by basvodde** [comment]
Ok, I tried on my Mac with gcc and clang, both didn't give the warning. Could you share what compiler and platform you are using ?

(you did have other warnings in the code you copied)

**Comment by engsergiosoares** [comment]
I'm using MinGW64 on Windows10.

This the full build log (running on Eclipse CDT):
```
10:53:13 **** Rebuild of configuration Debug for project false_warning ****
Info: Configuration "Debug" uses tool-chain "MinGW GCC" that is unsupported on this system, attempting to build anyway.
Info: Internal Builder is used for build
g++ "-IC:\\cpputest\\include" -O0 -g3 -Wall -c -fmessage-length=0 -o false_warning.o "..\\false_warning.cpp" 
In file included from C:\cpputest\include/CppUTest/TestHarness.h:40,
                 from C:\cpputest\include/CppUTest/CommandLineTestRunner.h:31,
                 from ..\false_warning.cpp:1:
..\false_warning.cpp: In member function 'virtual void TEST_false_warning_tests_function_pointer_no_variable_Test::testBody()':
C:\cpputest\include/CppUTest/UtestMacros.h:138:71: warning: the address of 'int function1(int)' will never be NULL [-Waddress]
       UtestShell::getCurrent()->assertEquals(true, StringFrom(expected).asCharString(), StringFrom(actual).asCharString(), text, file, line); \
                                                                       ^
C:\cpputest\include/CppUTest/UtestMacros.h:127:3: note: in expansion of macro 'CHECK_EQUAL_LOCATION'
   CHECK_EQUAL_LOCATION(expected, actual, NULLPTR, __FILE__, __LINE__)
   ^~~~~~~~~~~~~~~~~~~~
..\false_warning.cpp:19:2: note: in expansion of macro 'CHECK_EQUAL'
  CHECK_EQUAL(function1, func_ptr);
  ^~~~~~~~~~~
g++ -o false_warning.exe false_warning.o "C:\\cpputest\\src\\CppUTest\\libCppUTest.a" "C:\\cpputest\\src\\CppUTestExt\\libCppUTestExt.a" 

10:53:14 Build Finished. 0 errors, 1 warnings. (took 900ms)
```


And this is my full code:

```
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/TestHarness.h"

TEST_GROUP(false_warning_tests)
{

};

int function1(int a)
{
	return 0;
}

//Warning
TEST(false_warning_tests, function_pointer_no_variable)
{
	int (*func_ptr)(int);
	func_ptr = function1;
	CHECK_EQUAL(function1, func_ptr);
}

//No warning
TEST(false_warning_tests, function_pointer_with_variable)
{
	int (*func_ptr)(int);
	int (*expected_func_ptr)(int);
	func_ptr = function1;
	expected_func_ptr = function1;
	CHECK_EQUAL(expected_func_ptr, func_ptr);
}

int main(int ac, char** av)
{
    return CommandLineTestRunner::RunAllTests(ac, av);
}
```

**Comment by jgonzalezdr** [comment]
You should use the test macro POINTERS_EQUAL instead of CHECK_EQUAL, and the warning will disappear.

**Comment by basvodde** [comment]
Or FUNCTIONPOINTERS_EQUAL.

Still the warning is strange. I don't see where it comes from and cannot replicate it.

**Comment by jgonzalezdr** [comment]
The warning comes from passing a function directly to StringFrom(). Just put `SimpleString a = StringFrom(function1);` and the warning is emitted (if -Wall is enabled). I've tested that with GCG 7, 8 and 9 in Linux, and same versions of MinGW in Windows. BTW, clang 9 does not give any warning.

The problem here is that when passing a function or function pointer (with a signature different from void(*)()), a C++ compiler shall give more preference to the overload of StringFrom that takes a `bool` instead of the one that takes a `const void *` or `void(*)()`, and as a consequence GCC legitimately warns (since -Werror is activated by -Wall) that the argument will always take the same value (true) since it will never be NULL.

When passing a variable the compiler does not give a warning (even if it still is doing a conversion to bool) because -Werror only applies to functions converted to bool, not to function pointers converted to bool.

Using CHECK_EQUAL to compare pointers is a very bad idea, because if the assertion fails because the pointers are different the error message will moan that it expected <true> but was <true>, (or <false> for NULL pointers) which will be very confusing to the user.

Bas, you probably don't see the warning because you are compiling using CppUTest installed in a "standard" place. It seems that GCC ignores that warning if it happens in macros defined in files which are in the "default" include paths (/usr/include, /usr/local/include, etc.). I don't know what these "standard" paths are for MacOS. Anyway, just pass a "-I" option to the compiler with the path to your CppUTest "working" directory and the warning will appear.

**Comment by basvodde** [comment]
Ok. Any good way to solve it, other than saying "don't do that" ?

**Comment by jgonzalezdr** [comment]
The only way I can think of avoiding users to misuse CHECK_EQUAL it is to add a C++11 "static_assert" that checks that CHECK_EQUAL is not used with pointers, or some complicated form of template meta-programming to redirect to the proper function.

That would require of course conditional compilation to enable this only if the compiler supports at least C++11. 

I know you don't like adding template-related stuff or conditional stuff, but if you want I may give a try.

**Comment by basvodde** [comment]
Nah, don't want to go there. There is no way to make a better matching StringFrom ?

**Comment by jgonzalezdr** [comment]
AFAIK with arbitrary function pointers there is no simple way to solve this, because if there is an overload that accepts a `bool` (as it happens with StringFrom), the conversion to bool will always have preference over a conversion to `void(*)()` since the function signatures are different, and also over a conversion to `const void*`. Unfortunately, there is no such think like a "pointer to any function". 

Fortunately with other pointers this does not happen because conversion to `void*` has preference over conversion to bool. In that case `void*` actually acts as "pointer to anything (except functions)".

Let's see if someone else comes with some idea on how to avoid this.

**Comment by jgonzalezdr** [comment]
JFYI (possible "solution" when using modern compilers):

Adding the following to UTestMacros.h:
```cpp
#if __cplusplus >= 201103L
#define STATIC_ASSERT(condition, message) static_assert(condition, message)
#else
#define STATIC_ASSERT(condition, message)
#endif
```
Then adding this at the beginning of the CHECK_EQUAL_LOCATION macro:
```cpp
  STATIC_ASSERT( !std::is_pointer<decltype(actual)>::value && !std::is_pointer<decltype(expected)>::value, \
                 "Don't use CHECK_EQUAL to compare pointers!" ); \
```

**Comment by basvodde** [comment]
How to write a test for that?

**Comment by jgonzalezdr** [comment]
Good point, it's complicated to test compile-time assertions, that would require making a test that actually compiles something, which is an overkill here.

I have however a better option, which is making CppUTest smarter instead of stricter, and is also more testable, and pretty simple:

```cpp
#if __cplusplus >= 201103L
#define STRING_FROM(expr) \
    (((std::is_pointer<decltype(expr)>::value && std::is_function<std::remove_pointer<decltype(expr)>::type>::value) || \
      std::is_function<decltype(expr)>::value) ? StringFrom((void(*)())(expr)) : StringFrom(expr))
#else
#define STRING_FROM(expr) StringFrom(expr)
#endif

#define CHECK_EQUAL_LOCATION(expected, actual, text, file, line)\
  do { if ((expected) != (actual)) { \
      if ((actual) != (actual)) \
          UtestShell::getCurrent()->print("WARNING:\n\tThe \"Actual Parameter\" parameter is evaluated multiple times resulting in different values.\n\tThus the value in the error message is probably incorrect.", file, line); \
      if ((expected) != (expected)) \
          UtestShell::getCurrent()->print("WARNING:\n\tThe \"Expected Parameter\" parameter is evaluated multiple times resulting in different values.\n\tThus the value in the error message is probably incorrect.", file, line); \
      UtestShell::getCurrent()->assertEquals(true, STRING_FROM(expected).asCharString(), STRING_FROM(actual).asCharString(), text, file, line); \
  } \
  else \
  { \
    UtestShell::getCurrent()->assertLongsEqual((long)0, (long)0, NULLPTR, file, line); \
  } } while(0)
```
The only change done on the original macro is replacing `StringFrom` with `STRING_FROM`.

**Comment by jgonzalezdr** [comment]
This solution could be applied globally without breaking compatibility to all StringFrom usages by modifying SimpleString:
- The current StringFrom functions are renamed to StringFrom_ or StringFormInternal or something like this.
- The macro in the previous comment is added to SimpleString.h but renamed to StringFrom (and calling of course the renamed C++ functions).

However, playing devil's advocate, if the smart guys that defined the C++ standards decided that an arbitrary pointer to function is better cast to bool than to `const void*` or `void(*)()`, and C++ users know by heart the implicit cast precendences, who are we to change that? ¯\\\_(ツ)\_/¯

**Comment by basvodde** [comment]
I mean, how can we test the assert_static statement ?

**Comment by jgonzalezdr** [comment]
If you want to go the compile-time error way, there is AFAIK no way to directly write a test. I can however think of two ways to test that indirectly:
1. Macro substitution: Don't test `static_assert` because it cannot be done using "standard" tests (since the test will not compile), but instead using macros replace `static_assert` or `STATIC_ASSERT` for something else that gives an error at runtime, like for example `#define STATIC_ASSERT(expr) if(!(expr)) { throw 0; }`, and then do a test that checks that the exception is thrown.
2. Compilation: Write a test that launches the C++ compiler to compile an auxiliary test file that should fail, and then check the results of compilation to ensure that the assertion failed. Of course, this is very complicated because the user can be using different compilers (and different versions!), and handling that would be a nightmare. In a project that I'm developing ([CppUMockGen](https://github.com/jgonzalezdr/CppUMockGen)) I use LibClang to check that generated code compiles properly, but porting this here is a bit of an overkill.

Another option that can be considered is to always fail at runtime (test-time) instead of at compilation-time, by defining for example `#define CPP11_ASSERT(condition, message) if((!condition)) { UtestShell::getCurrent()->fail(message, __FILE__, __LINE__); }`.

**Comment by jgonzalezdr** [comment]
Update: Just in case someone  wants to test the "silent" automatic selection of the proper StringFrom for functions and pointers to functions, the previous proposal is not good because it will cause warnings. This one is better:

```cpp
#if __cplusplus >= 201103L
template<bool B, typename T>
struct StringFromWrapper
{
    static SimpleString Call(T v) { return StringFrom(v); };
};
template<typename T>
struct StringFromWrapper<true, T>
{
    static SimpleString Call(T v) { return StringFrom((void(*)())(v)); };
};
#define STRING_FROM(expr) \
    StringFromWrapper<(std::is_pointer<decltype(expr)>::value && std::is_function<std::remove_pointer<decltype(expr)>::type>::value) || \
                      std::is_function<decltype(expr)>::value, decltype(expr)>::Call(expr)
#else
#define STRING_FROM(expr) StringFrom(expr)
#endif

#define CHECK_EQUAL_LOCATION(expected, actual, text, file, line)\
  do { if ((expected) != (actual)) { \
      if ((actual) != (actual)) \
          UtestShell::getCurrent()->print("WARNING:\n\tThe \"Actual Parameter\" parameter is evaluated multiple times resulting in different values.\n\tThus the value in the error message is probably incorrect.", file, line); \
      if ((expected) != (expected)) \
          UtestShell::getCurrent()->print("WARNING:\n\tThe \"Expected Parameter\" parameter is evaluated multiple times resulting in different values.\n\tThus the value in the error message is probably incorrect.", file, line); \
      UtestShell::getCurrent()->assertEquals(true, STRING_FROM(expected).asCharString(), STRING_FROM(actual).asCharString(), text, file, line); \
  } \
  else \
  { \
    UtestShell::getCurrent()->assertLongsEqual((long)0, (long)0, NULLPTR, file, line); \
  } } while(0)
```

**Comment by basvodde** [comment]
I appreciate all the solutions. I've been thinking about it quite a lot and decided not to do any of that. Instead, I'm going to close this with "won't fix". Whenever this happens, it is better to use the FUNCTIONPOINTERS_EQUAL and that should resolve the warning.

I did enjoy the discussion and the topic. More template weirdness is at: https://www.youtube.com/watch?v=zxDzMjfsgjg
