### ISSUE TITLE
UtestShell::setCrashOnFail() does not work for Deallocating non-allocated memory failures

### ISSUE THREAD

**Issue by StephenHillAtViaivi** [cpputest/cpputest#1709]
If I call UtestShell::setCrashOnFail() and then force a 'Deallocating non-allocated memory' failure in my test thus:
```
char *pBlock = (char*)malloc(10);
free(pBlock+1);
```
I do not get the expected crash; instead I just get a warning.
Debugging this, the problem seems to come from the use of TestTerminatorWithoutExceptions() in the MemoryLeakWarningReporter class.
The fix I have found is to change it to:
```
class MemoryLeakWarningReporter: public MemoryLeakFailure
{
public:
    virtual ~MemoryLeakWarningReporter() _destructor_override
    {
    }

    virtual void fail(char* fail_string) _override
    {
        UtestShell* currentTest = UtestShell::getCurrent();
        currentTest->failWith(FailFailure(currentTest, currentTest->getName().asCharString(), currentTest->getLineNumber(), fail_string), UtestShell::getCurrentTestTerminator());
    } // LCOV_EXCL_LINE
};

```

**Comment by CiderMan** [comment]
I'm happy to pick this up but I think that it first needs PR #1430 to be delivered, which has been stalled for the last 2 years. Calling `UtestShell::getCurrentTestTerminator()` will return an appropriate terminator, but which may use exceptions. While this works for you, I assume that it may not work in all environments.

@basvodde Any chance that we could get #1430 completed so that I can pick this up?
