### ISSUE TITLE
Any Plans To Make CppUTest 64 Bit Ready?

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#174]
Just wondering, because I accidentally compiled it with a 64 bit compiler...

It would be pretty easy to make the code 64 bit-ready, but considerably harder to maintain 32-bit compatibility at the same time...

Example:
You need StringFrom(size_t) (for 64 bit).
You need StringFrom(uint32_t) (for Cpp library).
This is considered a redeclaration by 32 bit compiler.
You need unsigned long long etc. for 64 bit.
32 bit compiler (iso c98) does not know it.
etc. etc.

**Comment by mmidor** [comment]
Yeah, we are struggling with incorrectly written unit tests, and the issue has been closed a looong time ago :(

**Comment by mmidor** [comment]
Why to explicit support 64 bit platforms ? Let me explain.
We are working on three platforms:
* development environment, 64bit PC
* testing environment: 32 or 64 bit
* destination environment: 32 bit DSP

The code contains function returning 64bit results and I found that people used to use LONGS_EQUAL to check the returned values.
Obviously, this will work correctly only for our development 64bit PC, but not for the others, especialy destination Texas DSP platform.

Now, the fastest way to avoid this issue is to use inline comparison, for example CHECK_TRUE(retval64 == expect64);
The inconvenient way is to check separatelly lower and upper 32 bit halves of 64bit value. And I'm sure that people because of unawareness and lazyness will not use the correct way.

I'm aware that not all platforms support long long int and simply extending LONGS_EQUAL to always work on long long int is not possible, thus this extended functionality should be dependent on what CMake detect during the build preparation and, for convenience, on user given preprocessor symbols, and offer separate set of macros.

**Comment by Andne** [comment]
Is there a reason you're using the 64-bit compiler when your target environment is 32-bit?  I have a 64-bit PC at work and as long as I use a 32-bit compiler it acts like the target environment.

**Comment by mmidor** [comment]
In a big team distributed over a few locations it is hard to say what kind of tool people are using. Mostly Visual Studio, some Mingw and Cygwin. BTW, as I mentioned, if code uses uint64_t type, we cannot use  tests taking long (aka int32_t) as argument and loosing half of the bits.

**Comment by Andne** [comment]
Ok, so I can understand having support for a uint64_t type (`long long` on most platforms I think), but that seems independent of the bitness of the platform.

In reality, I'm not overly fond of the macros all being based on the compiler built-in types since I feel that when building across different platforms sometimes the macros won't correctly line up against the types in your code (I use `stdint.h` in my code) and as a result the comparisons may or may not be what you want just by changing which compiler you use.

**Comment by arstrube** [comment]
I would much prefer bit-exact type macros based on stdint types myself. With inbuilt types and no long long, CppUTest will always have some problems on the Windows platform which has 64 bit addresses but 32 bit longs (it has some problems internally as well).

As far as I know, one reason we are not using stdint is that CppUTest is supposed to be able to build without the standard C library.

Where I work, bit-exact types are almost exclusively used, either stdint or homemade (or third-party supplier dictated) ones. Myself, I have a strong preference for stdint, because the compiler takes care of doing the right thing for each particular platform.

**Comment by arstrube** [comment]
This issue, originally, was about the internal problems on Windows :-)

Using stdint.h is kind-of a different issue.

**Comment by mmidor** [comment]
Love to hear @arstrube you agree with me - I'm using stdint.h too wherever possible and persuading people to do the same (it helps a lot every time when working on the common code for different platforms). 
Tending to make CppUTest such extremely portable seems to be a serious evolution bottleneck. 

Anyway - there should be a method good for testing any type of integer numeric data. Maybe even for arrays. Maybe the solution is to treat the input as an array of bytes and compare it one-by-one? 
Number of bytes can be obtained by `sizeof(expected_value)` or even `sizeof(-25)`. 
Booth arguments have to be of exact size (`INTEGERS_EQUAL(15, 15LL)` should emit error as `sizeof(int) != sizeof(long long int)`).
Having such a macro it doesn't longer matter how big integer is supported on the current platform (and some supports `int128_t` or SSE specific type, also 128bit).
