### ISSUE TITLE
CMake build issues - missing CppUTestTargets.cmake

### ISSUE THREAD

**Issue by Servomex-ivisser** [cpputest/cpputest#1767]
Your build instructions are a little confusing. From the readme.md
```bash
git clone https://github.com/cpputest/cpputest.git
cmake -B cpputest_build
cmake --build cpputest_build
```
Am I supposed to make this directory? Or should this directory already exist? I couldn't find it, so I made it.
Beyond that, the project builds fine. I now have:
* /home/user/cpputest  = the source / git clone
* /home/user/cpputest-4.0 = the build output from the above

I suspect at this juncture, something is already wrong for unknown reasons.

Linking my project with CppUTest I get (excerpt)...
```bash
CMake Error at /home/user/cpputest-4.0/CppUTestConfig.cmake:29 (include):
  include could not find requested file:

    /home/user/cpputest-4.0/CppUTestTargets.cmake
```
The CppUTestConfig.cmake in my build directory looks like this around line 29:
```cmake
set_and_check(CppUTest_INCLUDE_DIRS "/home/user/cpputest/include")
if(NOT TARGET CppUTest)
  include("${CMAKE_CURRENT_LIST_DIR}/CppUTestTargets.cmake")
endif()
set(CppUTest_LIBRARIES CppUTest CppUTestExt)
```
And looking for the missing file CppUTestTargets.cmake, I find it here...
```bash
find . -name CppUTestTargets.cmake
./CMakeFiles/Export/4306f34d0d0a58e19d5744ed1e2a0d78/CppUTestTargets.cmake
```
Should file CppUTestTargets.cmake be in this directory at this stage? Or should the cmake config somehow be able to find it here?

**Comment by SpuriousInterrupt** [comment]
I also noticed that the output/binary directory does not include the include directory and all headers within.
That is somewhat surprising. And maybe even indicative of build issues maybe?

I expected that these header files would be (re-)published in the build area, so that I would need to point my project at just the build area (where I find the generated `CppUTestConfig.cmake`) and my project gets everything from there; the headers and all libraries.
I could effectively remove the CppuTest source directory after I built it, if I wanted to. Because nothing in it would be referenced by any project linking with CppUTest.

**Comment by SpuriousInterrupt** [comment]
[SOLVED]
Go to the output directory and run `sudo make install` from there.
This collates all the files into `/usr/local/lib` and `/usr/local/include`.

The build area cannot be used as a local build that one can import (`find_package()`) for CMake builds.

Sidenote:
I had to use `make install` from the build area to install, as `cmake --build --install ....` from the project area would not work for me. I get "ModuleNotFound" errors. This is on Mint 20.3.
