### ISSUE TITLE
Optimize the mock calls

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#22]
When having a lot of mock expectations, it goes really slow :) Needs to optimize this a bit.

**Comment by offa** [comment]
@basvodde Lot's of time is spent by coping Strings (eg. `SimpleString::copyToNewBuffer()` or `SimpleString::StrNCpy`).

I've experienced this by tests using thousands of (checked) mock calls, which increased the test runtime dramatically. There's even a notable difference between 10 or 100 calls.

**Comment by offa** [comment]
In my case I have gained a ~ 150 times faster test using following workaround:

Instead of using `expectNCalls()` I have ignored calls and instead count calls using `getData()` / `setData()` within the mocked function. After call to the CuT i've used a `CHECK_EQUAL()` to compare the expected with the actual calls.

Using `mock("XYZ").disable()` instead of `mock("XYZ").ignoreOtherCalls()` has same runtime btw.

**Comment by jgonzalezdr** [comment]
The PR that I submitted a while ago may also help improve runtime performance when using lots of expectNCalls, because with these modifications the expected calls list is traversed much faster, as it has much less entries.

A different problem would be if there where hundreds of calls to different methods, in that case the runtime performance could be improved by using an auxiliary hash table to locate entries by name faster, but I think that this case is rather rare when designing unit tests and therefore it's not worth dedicating effort to this.

**Comment by offa** [comment]
@jgonzalezdr  that is #1023 ?

**Comment by jgonzalezdr** [comment]
@offa Exactly.

**Comment by jgonzalezdr** [comment]
We could also check if some improvement can be achieved by replacing some arguments and return values that are of type "SimpleString" by "const SimpleString&", that would certainly reduce time wasted copying strings around unnecessarily.

**Comment by offa** [comment]
@jgonzalezdr I have tested your PR: There's a ***huge*** performance improvement. Even if there where 1000 - 2000 mock calls to check, my tested tests ran notable fast.

**Comment by basvodde** [comment]
I'm not sure it is worth optimizing the case with lots of different Mock calls ;) It feels there is something wrong with the test then.

**Comment by offa** [comment]
If there's no negative impact, performance improvement wont hurt.

Anyway, the `expectNCalls()` should get some speedup boost.

**Comment by basvodde** [comment]
If it simplifies the code, I'm for it. If it complicates it, then the code readability will hurt.

**Comment by offa** [comment]
Just to get you right: Are we talking about the case with different mocks or the `expectNCalls()` as  @jgonzalezdr's PR?

**Comment by basvodde** [comment]
Nah, @jgonzalezdr code will be integrated, will just be a question of time.

I mean further optimization for the case of using a lot of ExpectOneCall, which to me would probably be a test smell.

**Comment by offa** [comment]
I see – totally agree with you here.

**Comment by offa** [comment]
@basvodde any news on this?

**Comment by basvodde** [comment]
No news, but it will continue, don't worry (yet)

**Comment by jgonzalezdr** [comment]
@basvodde: PR #1023 has already been merged, so you can now close the 11th oldest issue still open on CppUTest ;-)

**Comment by basvodde** [comment]
Oki!
