### ISSUE TITLE
Create a development guideline

### ISSUE THREAD

**Issue by katcipis** [cpputest/cpputest#293]
I think it would be a good idea to have a development guideline, and maybe some scripts that checks the code for this guidelines (like GStreamer).

I had this idea seeing that MockSupport.h has its indentation completely messed up, at least this (indentation :-) should have a clear guideline :-).

**Comment by itavero** [comment]
Tools I can recommend to fix/check formatting are [Artistic Style](http://astyle.sourceforge.net) and [Uncrustify](uncrustify.sourceforge.net).
The first tool is rather simple to configure, but less flexible.
The second tool has lots of configuration options and is more flexible.
Both are available for Linux, OSX and Windows, if I remember correctly.

Since you still need to define most of the guidelines, I'd suggest going with one of the standards Artistic Style supports and using that tool.

**Comment by thetic** [comment]
https://clang.llvm.org/docs/ClangFormat.html

**Comment by offa** [comment]
#1267
