### ISSUE TITLE
Question: macro/function call to exit a test case successfully?

### ISSUE THREAD

**Issue by ajf58** [cpputest/cpputest#426]
I was wondering if there's a way to exit a `TEST_CASE` before reaching the end of the statement block. This would be the opposite of the `FAIL` macros functionality, i.e. the test case is completed and marked as a passed. My understanding is that ultimately the `FAIL` macro leads to the `failWith` function call, so is it simply a case of having a call to `terminator.exitCurrentTest()`? Is there a better idiom for this?

``` c++
void UtestShell::failWith(const TestFailure& failure, const TestTerminator& terminator)
{
hasFailed_ = true;
getTestResult()->addFailure(failure);
terminator.exitCurrentTest();
}
```

The motivation for this is to be able to mock a function that is used in a mutlithreaded application, which in normal use would cause the code under test to block (pend on an inter-thread message queue).

As a meta-qestion: is this the best place to ask questions, or is there a cpputest-users mailing list or similar?

**Comment by arstrube** [comment]
@ajf58 If it is still relevant to you - I just had the opportunity to test an infinte while loop in main() in some legacy code. Leaving aside the main() issue, here is something that I think works well to exit the loop successfully. There are a few preconditions, nevertheless.

1. An exit criterium (e.g. so many times through the loop, or whatever)
2. A function that gets called from within the loop which you can stub
3. Basically, you will have those (the place where you would have called EXIT_TEST_SUCCESSFULLY().
4. You must write the stub in C++.

Now for the interesting stuff. Instead of the macro, which we don't have or want, at the place where you would have used the macro, simply do:
```c++
throw "Success!";
```
In the test case, wrap the function under test like this:
```c++
    try {
        function_with_infinite_loop();
    }
    catch(char const* s) {
        STRCMP_EQUAL("Success!", s);
    }
```
This is really easy, and the STRCMP_EQUAL is strictly optional ;-).
