### ISSUE TITLE
Error in Release-mode with VisualStudio 2010

### ISSUE THREAD

**Issue by ActionLuzifer** [cpputest/cpputest#440]
Hay, when I compile cpputest and try to run 'alltests' then i get an exception after the third test.
This seems to happen when Optimizations are enabled, whats the normal case in 'Release'-Mode.

I wrote a little testgroup with one TEST which has only a 'FAIL("Ups")' inside and i get the same result.

It's since 3.6 to the actual master. Older versions won't compile :(
I have MS VS 2010 SP1 - Professional and Win7 Professional x64

Some one else with this problem or know how to catch whats wrong?

**Comment by Andne** [comment]
There is a now-known issue with Visual C++ optimizations and the exception handling of CppUTest.  Generally speaking, the easiest solution is to disable optimizations.  The issue seems to be where the execution path goes through a couple of extern 'c' functions.  With optimizations enabled, the compiler detects these during some inlining and removes the catch block as being not required.  So far, I don't think much work has been done to find a different work-around, and I'm on the fence as to if there is much value in doing so anyways, since when running a Visual C++ build most likely the build is running on Windows (technically it could be for CE or Windows Phone I suppose) and so performance is probably not a major concern vs. a working unit test tool.

**Comment by arstrube** [comment]
This makes sense to me. Since our current solution is not to switch on optimisations for the release built, I guess we'll just leave it the way it is now...

**Comment by arstrube** [comment]
@ActionLuzifer I just realized that when I answered I thought this was a different thread... I have fixed the Release version by taking out the -O2 parameter from the Release configuration (which I referred to above as "the way it is now" above). As @Andne  pointed out, this appears to be the easiest solution for now...
