### ISSUE TITLE
Visual Studio 2010: Crashes in AllTests Release executable

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#465]
There are quite a few crashing test cases in UTestTest.cpp and some more in MemoryLeakWarningTest.cpp. There may be more. I was alerted to the crashes by a co-worker who uses CppUTest with VS2010.

I am currently investigating the issue.

I am also experiencing a strange linker problem in the Debug configuration:

```
2>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
```

**Comment by arstrube** [comment]
The following tests are affected:
```
TEST(MemoryLeakWarningTest, FailingTestDoesNotReportMemoryLeaks)
TEST(MemoryLeakWarningGlobalDetectorTest, turnOffNewOverloadsCausesNoAdditionalLeaks)
TEST(MemoryLeakWarningGlobalDetectorTest, destroyGlobalDetector)
TEST(MemoryLeakWarningGlobalDetectorTest, MemoryWarningPluginCanBeSetToDestroyTheGlobalDetector)
TEST(MemoryLeakWarningWarningThreadSafe, turnOnThreadSafeNewDeleteOverloads)
TEST(UtestShell, FailWillIncreaseTheAmountOfChecks)
TEST(UtestShell, PassedCheckEqualWillIncreaseTheAmountOfChecks)
TEST(UtestShell, MacrosUsedInSetup)
TEST(UtestShell, MacrosUsedInTearDown)
TEST(UtestShell, TeardownCalledAfterTestFailure)
TEST(UtestShell, TestStopsAfterTestFailure)
TEST(UtestShell, TestStopsAfterSetupFailure)
TEST(UtestShell, DestructorIsCalledForLocalObjectsWhenTheTestFails)

**Comment by arstrube** [comment]
The problem occurs only if /O2 (Maximize Speed) is selected. The most practical solution would thus be to disable optimizations in the Release build.

Is there an easy way of pinpointing exactly what is causing problems here?

**Comment by basvodde** [comment]
Thanks!

**Comment by jwgrenning** [comment]
Can you run the tests in the debugger and go on a bug hunt?

It would be good to answer if it is a CppUTest problem or a VS problem.

**Comment by arstrube** [comment]
There are no crashes with gcc -O3.

**Comment by jwgrenning** [comment]
Does -O3 mean he same thing in both?  I thick it would be surprising if 
the implementations were the same and had the same defects.

Thanks

**Comment by arstrube** [comment]
Yes, -O3 in gcc means optimize for maximum speed, and /O2 in MSVC mean optimize for speed (no distinction between more or less ;-).

As you  say, I suspect a defect in MSVC rather than in CppUTest.

Maybe it's possible to "debug" - MS discourages combining optimisation with the debug switch, though. I'll give it a shot.a

**Comment by jwgrenning** [comment]
If O3 and debug do not crash the same way, you may be able to run the 
debugger with out the debug switch.  You'd probably have asm only. You'd 
need the intermediate asm with C++ as comments to figure it out.  This 
is the old fashion way :-)

**Comment by Andne** [comment]
I ran into this with VS2010+ and was chasing it a bit, but stopped when I found that it was related to optimizing.  It seems like a possible conflict between the optimizer, exceptions and extern "C".  When optimizing, if an exception occurs, it appears that the call stack unwinding won't pass through the extern "C" functions that setjmp/longjmp uses, which results in an unhandled exception.  I had a different behavior where it was failing several tests but not crashing, but I don't remember what it was anymore, I think I got it by changing the exception handling logic that was being used.

**Comment by basvodde** [comment]
Yes, we have a bug report on some gcc compiler related to that to from @simshi 

@simshi do you remember which one this was? It was hard to resolve!

@arstrube Could you try the /O2 with stdc++ lib turned off (which turns off the use of exception handling)?

**Comment by simshi** [comment]
This one? https://github.com/simshi/cpputest/commit/a1ebcb675f9864279bbf6be39c6bb32b18c8bae2#commitcomment-2404328

http://stackoverflow.com/questions/7781342/a-mechanism-to-ensure-exception-propagation-when-mixing-c-and-c-code

**Comment by Andne** [comment]
I built with /O2 (max speed), /EHsc (Enable C++ Exceptions) and using stdlib++ and ran the CppUTest test suite (only CppUTest, not CppUTestExt) - crashes during TEST(UTestShell, DestructorIsCalledForLocalObjectsWhenTheTestFails), 4th test ran

I built with /O2 (max speed), /EHsc (Enable C++ Exceptions) and CPPUTEST_STD_C_LIB_DISABLED and ran the test suite - 385 tests, 373 ran, 12 ignored, 0 fails

I built with /O2 (max speed), /EHs (Enable C++ Exceptions with Extern C functions) and using stdlib++ and ran the test suite - 399 tests, 387 ran, 12 ignored, 7 failures (all in TestHarness_cTest.cpp, all on this check - CHECK(!hasDestructorOfTheDestructorCheckedBeenCalled)) (Side note, I forgot to change the property in both projects the first time, and it passed all tests when building the library with /EHs and the tests with /EHsc)

I built with /O2 (max speed), /EHa (Enable C++ Exceptions with SEH Exceptions) and using stdlib++ and ran the test suite - same results as with /EHs (I checked the mixed projects, same there too)

I built with /O1 (minimize size), /EHsc (C++ Exceptions) and stdlib++ and ran the test suite - crashes during TEST(UTestShell, DestructorIsCalledForLocalObjectsWhenTheTestFails), 4th test ran

I started ignoring tests to see if I could get a good run with /O2, had to ignore these tests
IGNORE_TEST(UtestShell, DestructorIsCalledForLocalObjectsWhenTheTestFails)
IGNORE_TEST(UtestShell, TestStopsAfterSetupFailure)
IGNORE_TEST(UtestShell, TestStopsAfterTestFailure)
IGNORE_TEST(UtestShell, TeardownCalledAfterTestFailure)
IGNORE_TEST(UtestShell, MacrosUsedInTearDown)
IGNORE_TEST(UtestShell, MacrosUsedInSetup)
IGNORE_TEST(UtestShell, FailWillIncreaseTheAmountOfChecks)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_THROWS_whenWrongThrow)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_THROWS_whenDoesntThrow)
IGNORE_TEST(UnitTestMacros, CompareNFirstCharsWithLastCharDifferent)
IGNORE_TEST(UnitTestMacros, CompareNFirstCharsWithEmptyString)
IGNORE_TEST(UnitTestMacros, CompareNFirstCharsWithDifferenceInTheMiddle)
IGNORE_TEST(UnitTestMacros, CompareNFirstCharsWithUpperAndLowercase)
IGNORE_TEST(UnitTestMacros, FailureWithDOUBLES_EQUAL)
IGNORE_TEST(UnitTestMacros, FailurePrintHexOutputForPointers)
IGNORE_TEST(UnitTestMacros, FailureWithBYTES_EQUAL)
IGNORE_TEST(UnitTestMacros, FailurePrintHexOutputForLongInts)
IGNORE_TEST(UnitTestMacros, FailureWithSTRCMP_NOCASE_CONTAINS)
IGNORE_TEST(UnitTestMacros, FailureWithSTRCMP_CONTAINS)
IGNORE_TEST(UnitTestMacros, failing_CHECK_EQUAL_withParamatersThatDontChangeWillNotGiveAnyWarning)
IGNORE_TEST(UnitTestMacros, failing_CHECK_EQUAL_WithExpectedBeingEvaluatesMultipleTimesWillGiveAWarning)
IGNORE_TEST(UnitTestMacros, failing_CHECK_EQUAL_WithActualBeingEvaluatesMultipleTimesWillGiveAWarning)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_EQUAL)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_FALSE)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_TRUE)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK_TEXT)
IGNORE_TEST(UnitTestMacros, FailureWithCHECK)
IGNORE_TEST(UnitTestMacros, FAILWillPrintTheFileThatItFailed)
IGNORE_TEST(UnitTestMacros, FAILMakesTheTestFailPrintsTheRightResultAndStopsExecuting)
IGNORE_TEST(SetPointerPluginTest, installTooMuchFunctionPointer)
IGNORE_TEST(MemoryLeakWarningTest, FailingTestDoesNotReportMemoryLeaks)

If I had to guess I'd say it's every test that checks for behavior during a failure.  Looks like it's definitely something to do with exceptions and optimizing.  I found this page on exception handling in  Visual C++, has one line that I think is what is being seen:
http://members.gamedev.net/sicrane/articles/exception.html
In debug mode for MSVC 2003, this will print "Moo." In release mode, with /EHsc (the default enable exception handling flag), the compiler sees that RaiseException(), as an extern "C" function, can't raise a C++ exception. Since catch (...) is only supposed to catch C++ exceptions, the compiler then removes the catch handler as dead code. This can lead to wonderfully bizarre and inconsistent behavior between debug and release builds14). Using /EHs or /EHa without /EHc will prevent the compiler from removing the catch block.

**Comment by Andne** [comment]
I did some more chasing and compared the assembly, looks like the issue is occuring during the compilation of Utest::run()

With optimizations disabled:
```assembly
; 499  : {
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?run@Utest@@UAEXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	push	ecx
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-220]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR __$EHRec$[ebp], esp
	mov	DWORD PTR _this$[ebp], ecx
; 500  :     try {
	mov	DWORD PTR __$EHRec$[ebp+12], 0
; 501  :         if (PlatformSpecificSetJmp(helperDoTestSetup, this)) {
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	push	OFFSET _helperDoTestSetup
	call	_PlatformSpecificSetJmp
	add	esp, 8
	test	eax, eax
	je	SHORT $LN2@run
; 502  :             PlatformSpecificSetJmp(helperDoTestBody, this);
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	push	OFFSET _helperDoTestBody
	call	_PlatformSpecificSetJmp
	add	esp, 8
$LN2@run:
; 503  :         }
; 504  :     }
	jmp	SHORT $LN6@run
__catch$?run@Utest@@UAEXXZ$0:
; 505  :     catch (CppUTestFailedException&)
; 506  :     {
; 507  :         PlatformSpecificRestoreJumpBuffer();
	call	_PlatformSpecificRestoreJumpBuffer
; 508  :     }
```

With optimizations active:
```assembly
; 499  : {
	push	esi
	mov	esi, ecx
; 500  :     try {
; 501  :         if (PlatformSpecificSetJmp(helperDoTestSetup, this)) {
	push	esi
	push	OFFSET _helperDoTestSetup
	call	_PlatformSpecificSetJmp
	add	esp, 8
	test	eax, eax
	je	SHORT $LN2@run
; 502  :             PlatformSpecificSetJmp(helperDoTestBody, this);
	push	esi
	push	OFFSET _helperDoTestBody
	call	_PlatformSpecificSetJmp
	add	esp, 8
$LN2@run:
; 503  :         }
; 504  :     }
; 505  :     catch (CppUTestFailedException&)
; 506  :     {
; 507  :         PlatformSpecificRestoreJumpBuffer();
; 508  :     }
```

It looks like something is keeping the exception handling code from being generated.  My guess is that it's because PlatformSpecificSetJmp is an extern "C" function, so the compiler assumes no exceptions can occur inside it, so therefore it doesn't need an exception handler.  Is there a reason that SetJmp is still being used when the failure is caught via an exception instead of longjmp?

**Comment by basvodde** [comment]
The reason is that it caused less code in #if blocks :)
