### ISSUE TITLE
Successful CHECK_THROWS does not add to check count

### ISSUE THREAD

**Issue by klusark** [cpputest/cpputest#480]
When using CHECK_THROWS, it only increments the "checks" count when the test is successful. For example:

    .................................................
    OK (49 tests, 49 ran, 44 checks, 0 ignored, 0 filtered out, 21 ms)

And here we have one exception test failing.

    .................................
    filename.cc:128: error: Failure in TEST(test_group, test_name)
            expected to throw std::exception
    but threw nothing

    ................
    Errors (1 failures, 49 tests, 49 ran, 45 checks, 0 ignored, 0 filtered out, 50 ms)

Notice that it has 44 checks in the first case, and 45 in the second.

**Comment by arstrube** [comment]
I looked into this one. The reason for this bug is easy enough to see (use of `UtestShell::fail()` rather than `UtestShell::failWith()`, which unconditionally increments the check count, but only in case of failure.

I tried to use `UtestShell::failWith()` instead, but that is tricky since the whole thing is inplemented as a macro rather than a method of UtestShell.

@basvodde can you see any solution for this dilemma?

**Comment by arstrube** [comment]
Not to worry. I found another way...

**Comment by arstrube** [comment]
I believe I fixed this one, too.

**Comment by basvodde** [comment]
Closing.
