### ISSUE TITLE
How to use CppUtest's API

### ISSUE THREAD

**Issue by FeiCao** [cpputest/cpputest#651]
I have a question about the CppUtest's API, for example, I want to know how to use 'withParameterOfType'  and Why the third parameter of 'withParameterOfType' must be 'void* object = (void*)1'??  So, I hope I can find some documents to scan the function of the CppUtest's API. Thank you!!

**Comment by arstrube** [comment]
Hi there,

There is a nice example on cpputest.github.io.

You obviously looked at the test cases (which is a very good idea), but the test cases tend to be a bit minimalistic in places, rather than worked examples :)

So, yes, the third argument must be cast to `(void*)`, because the address of the custom object is passed as a void* since it could be anything (even a pointer with the value 0x0000001), but it certainly doesn't have to be 1. In reality, it will be your the address of your custom object.

Another point worth noting is that the type of the object is matched via its name (the first string), not it's C++ type.

Finally, to use withParameterOfType() sensibly, you need a comparator for your custom object, that gets installed using the same name.

I have a worked example at https://github.com/arstrube/MiscellaneousTests/tree/master/WeirdMockTests -- but beware of The Bug (#650)!

**Comment by arstrube** [comment]
The example I linked was originally written to solve one very specific problem, not for public consumption. I think you will still find it useful, though. Remember to check out the commit history as well. It will show you, among other things, how it should be (but doesn't work) and various alternatives, both working and not-working.

**Comment by arstrube** [comment]
Play around with the tests, too, to see them fail.

**Comment by basvodde** [comment]
Fixed, I assume. Closing. Please re-open when incorrect.
