### ISSUE TITLE
[cppumock] onobject for const-methods

### ISSUE THREAD

**Issue by ZahlGraf** [cpputest/cpputest#803]
Hi

How can I use the `onObject(void *)` method from `MockActualCall` inside const-methods?
Here the `this` pointer points to a const object, thus I cannot give the this pointer to the `onObject` method.

Code example:

``` cpp
virtual bool isSetting(std::string const &rKey) const
{
  mock().actualCall("IDatabaseMock::isSetting").onObject(this).withStringParameter("rKey", Key.c_str());

  return mock().returnIntValueOrDefault((int)false) ? true : false;
}
```

(This example does not compile, since the `this` pointer points to a constant object, but `onObject` expects a pointer to a non-const object.)

Is there another method?

Best regards

**Comment by ryanplusplus** [comment]
It's not perfect, but you can use withConstPointerParameter("this", this)
instead.

Ryan

**Comment by ZahlGraf** [comment]
@ryanplusplus 
Thanks, that sounds like a quite nice workaround :) 
I will give it a try...

**Comment by Andne** [comment]
I usually use const_cast<type *>(this).

@basvodde Is there a reason onObject doesn't just take const void *?  I'm not too familiar off the top of my head with the internals of CppUMock, so I don't know if the stored pointer needs to be non-const for a reason or not.  I wouldn't think it needs to modify the class at all though (especially since it's a void *), so it seems like that would work ok.

**Comment by ZahlGraf** [comment]
@Andne 
Yes having a onObject that can take a const void* would be the best solution. Hopefully we can get it in one of the next releases.

**Comment by basvodde** [comment]
I can't think of a good reason @Andne

**Comment by basvodde** [comment]
Seems this is done already, closing it.
