### ISSUE TITLE
V3.7.1 has .sln file referencing missing files in Visual Studio Pro 2013

### ISSUE THREAD

**Issue by MisterScott** [cpputest/cpputest#811]
On downloading and unzipping cpputest-3.7.1, I opened CppUTest.sln.  
In project CppUTest, it shows the following files which are not present in the .zip file:
1.  include\CppUTest\EqualsFailure.h   --> contents appear to have been moved to TestFailure.h
2.  include\CppUTest\Failure.h --> used?
3.  include\CppUTest\MemoryLeakWarning.h --> not sure, now MemoryLeakWarningPlugin.h?
4.  include\CppUTest\MockTestOutput.h --> used?
5.  include\CppUTest\NullTest.h  --> not sure, now NullTestPlugin.h?
6.  src\Platforms\VisualCpp\Platform.h  --> now UTestPlatform.h?
7.  include\CppUTest\RealTestOutput.h  --> used?
8.  include\CppUTest\SimpleStringExtensions.h --> not sure, now in SimpleString.h?
9.  include\CppUTest\TestInstaller.h --> appears to be defined in UTest.h
10.  include\CppUTest\VirtualCall.h --> used?

Plus any files which are needed but not included in the .sln file.

Is Visual Studio currently intended to be supported, please?

Thank you,
Scott

**Comment by arstrube** [comment]
Hi Scott,

Visual Studio is fully supported. Most issues with VS have been fixed since 3.7.1 and are fine in the current Head. However, there has not been an official release since 3.7.2. You may want to try the current Head. I don't see any of these headers in the .vcxproj files (CppUTest_VS201x.sln).

Having said that, it appears that at least some of the superfluous header entries you mention are still around in project files for older versions of VC (CppUTest.sln, CppUTest.dsw), namely:
    - CppUTest.vcproj
    - CppUTest.dsp
While this doesn't seem to cause any harm, it should probably be fixed.

**Comment by arstrube** [comment]
@basvodde do we still need to keep this open? All of this (and more) should be fixed in Head, and for all I can tell we are not going to 'fix' 3.7.1 anymore.

**Comment by basvodde** [comment]
Ok closed.
