### ISSUE TITLE
Allow running tests in a shuffled/randomized order

### ISSUE THREAD

**Issue by WilcoBT** [cpputest/cpputest#865]
We previously used gtest and then the --gtest_repeat=[XXX] with  --gtest_shuffle to run the tests a few times in different orders to exclude ordering issues. I do see the repeat parameter on the website, but not the shuffle.
Are there any plans to add support for this function or estimations how to add it and how much trouble this would be?

**Comment by basvodde** [comment]
No, because if you run random and get random failures, then you'll need to know the random pattern in order to debug it. If it is purely random, it is only leading to guarenteed frustration :P

**Comment by arstrube** [comment]
Not necessarily. If you run the tests with -v, it is fairly easy to narrow down a problem (if it does occur, which most of the time it shouldn't).

**Comment by Andne** [comment]
The catch there is that if the tests are random, multiple runs with -v may not actually trigger the failure, especially if it's only when two specific tests run one after the other.  At that point, debugging becomes quite complicated since you have no guarantee that the error will occur on any given run.

Here's a thought - what if as part of running the tests on random, you could output to the test order to a file and then read in that file in order to execute the tests in the same order again?

**Comment by arstrube** [comment]
It can already be done:
```
whatevertest.exe -v >log.txt
```
The output (preferably a limited subset) can be fed into a debug run, if needed:
```
whatevertest.exe TEST(group, test5) TEST(group, test1) .....
```
An entirely different question is how much work the "randomness" would be to implement....

**Comment by WilcoBT** [comment]
Well, about the reproducability, I got the impression from the google variant that the randomness was based on a seed that was put in the log file(I at least see it on my console), so if you have an issue you could rerun with that seed to reproduce.

**Comment by mcergun** [comment]
any progress on this aspect?

**Comment by WilcoBT** [comment]
Not yet, we first have a release to finish.

But we are wondering if our fix will be meeting the requirements for backporting here or will be added to the changes that we have on the local checkout.

**Comment by rivuonna** [comment]
Check out PR #1181

**Comment by rivuonna** [comment]
Check out #1182
