### ISSUE TITLE
Value of 32 for SetPointerPlugin::MAX_SET too small

### ISSUE THREAD

**Issue by FrankLorenz** [cpputest/cpputest#882]
SetPointerPlugin::MAX_SET is hard-coded to 32 inside include/CppUTest/TestPlugin.h

I currently have the situation that I need to replace more than 32 functions by mocks and stubs for a rather complex C-code-module. 
If I do more than 32 UT_PTR_SET ( ...) inside setup(), tests fail with the error "Maximum number of function pointers installed!"

Perhaps such a low limit makes sense to let CppUTest run on limited embedded platforms, but for running on a PC host, it isn't necessary and just hinders workflow and design.

**Comment by basvodde** [comment]
Wow, more than 32 replacements :)

**Comment by FrankLorenz** [comment]
Well, I have some kind of MVC (model view controller) pattern. Of course the controller has heavy interaction with both model and view (and, because it's embedded development, with interfaces that control hardware).
If I want to test the controller as a seperate unit, I have to mock model and view. As the code and my tests grew, I was surprised that suddenly all the tests of the unit failed...

**Comment by arstrube** [comment]
Exactly what kind of pointers are you replacing (I have used UT_PTR_SET() for function pointer substitution (for all functions of a given module) and I am kind of almost surprised now that we never ran into the limit.

Probably the reason is that the function pointers we made all defaulted to the "real" implementation, and we only used UT_PTR_SET() for the ones we needed change to mocks / stubs.

So, while we had function pointers for possibly a hundred or so function, we never needed to set much more than a handful at any given time.

**Comment by arstrube** [comment]
p.s. @FrankLorenz in your case, defaulting to Mock may be a better choice.

BTW function pointers only make sense if you test Model and View in the same test executable as the Controller. Otherwise, why not let the linker do the work?

(We used FPs because it was a relatively small project and therefore made sense to have only one test executable for a dozen or so modules. In large projects, this would be unworkable and a test executable per unit makes more sense).

CppUTest itself tests a lot of "modules" within only two test executables and few or no function pointer substitutions.

**Comment by FrankLorenz** [comment]
Well, I took the approach James Grenning teaches in his book "TDD for embedded C".

Because I have C-code, "deaulting to Mock" would really mean to create seperate unit test executables for every unit, right? That would be a lot of work for me because my build puts all tests of all units into a single executable at the moment.
My quick solution is now to split the tests of the controller into several TEST_GROUPs. That's not a nice solution, but it works for me in this case.

**Comment by arstrube** [comment]
Well, yes and no. I have used both approaches. It really depends on the size of the units (some I have worked with I'd rather call components, with many sub-units), when they are big, separate executables make sense.

In the other case, it also depends on the layer structure, e.g. not every unit needs to mock every other unit (which is why defaulting to "real" implementation worked quite well for us).

Spliting into several test groups seems a good solution to me. Perhaps there is some natural way of splitting into groups, rather than just Group1, Group2, Group3, ... which I agree would not be very nice.

**Comment by Andne** [comment]
Is there a reason you can't split your build into several phases/layers?  I have a display project at work where I build the different layers of the software - low-level, middle, application in different projects and just move the headers and static library files from one to the next.  This allows me to do pretty much everything with just mocks.

Granted, I'm also working in C++, so even within a given module all I need to do is pass a different implementation of an interface into the unit I'm testing.  The very bottom layer is written in C though with a C++ adapter layer on top of it, so when I was testing the logic in the adapter layer I used the linker to bring in my stubs and mocks and I only link in the static library containing the real code at the final application level.

The other reason I did this is because I have several applications that use the other layers, so this way I only had to compile the shared code files once.

**Comment by FrankLorenz** [comment]
Well, of course it would be possible to split the build. But I don't know if its worth the work.
When I started using unit tests for the project I thought putting all together into a single build would be the natural way. 

And for my application, (model, view, controller pattern), if I implement a new feature, I usually extend all three parts. So splitting unit tests for model, view and controller to three different builds does not look like the most natural and easy way for me (at least it needs some time to refactor my build structure to let the tests run seamlessly during development).

**Comment by arstrube** [comment]
While that makes sense to me, if it were my tests, I would wonder why I need that many functions replaced for a single test? Maybe there's a different way? I mean, you've got to have 32 lines of UT_PTR_SET in your setup(), right?

**Comment by FrankLorenz** [comment]
Yes, I have 32 lines of UT_PTR_SET.
My Idea was to test controller, model and view seperately. But of course there is heavy interaction between the three, so writing test for them consumes a lot of time for doing all the mocking anyway. 

The only idea I have to reduce this is to take all three together as one unit and test them together.

**Comment by arstrube** [comment]
Somehow I'd think about breaking up the tests into manageable chunks, rather than testing an evern bigger monolith. :-)

I often have a test group per operation, but that is testing old-style legacy C code with functions that are mostly non-trivial...

**Comment by arstrube** [comment]
The more I think about it, the less I believe that CppUTest needs more than 32 function pointers in a single test....... I think that limit is quite generous.

I re-read your above reply. If you think that defaulting to mocks would require several executables, then we are not talking about the same thing. I was testing C code, but the basic principle would have to be the same for Cxx:

1. Every "real" function is replaced by a stub.
2. Every stub calls a function through a function pointer, which may be a mock, or the real code. Mine defaaulted to real code, but they might default to mock.
3. Use UT_PTR_SET for any that needed changing for a particular test (in my case, only those that needed mocking for that particular test).
4. Essentially, if you default to mock, you need to set the pointer only for the functions under test.

**Comment by FrankLorenz** [comment]
Well, I have C-code, too.
I don't know if I understand you completely here - if you replace every "real" function by a stub and use function pointer to switch between "real" and "mock", how do you handle this for the "real" executable for the target application?
I took the approach described in James Grennings book: if you have a function `void foo ( )` and what to enable switching between 'real' and 'mock', you change declaration in the header file to a function pointer:
`extern void (*foo) ( )`
And the 'real' defintion is then done like this:
`void fooImpl ( )
{
 [...]
}`

`void (*foo) ( ) = fooImpl;`
So all pointers default to the real implementation for the target build. To switch to the mock I need 'UT_PTR_SET' inside `setup()` for every function that is called by my unit under test within the current `TEST_GROUP`. Or do I miss something?

**Comment by arstrube** [comment]
I see.

1. I use the original headers
2. I let the "real" original function be mangled by C++
3. The wrapper is not mangled
4. I assign a default to each function pointer (the original)
5. I use UT_PTR_SET only on those that I need to mock

My question is really why you cut the TEST_GROUP the way you do? Certainly not every single test in your group needs all those 32++ functions mocked?

Just as an aside - if you really want to go that way, why not assign the pointers normally and leave them be forever? There seems to be no actual need in your case to revert them to the real implementation at the end of every single test? I assume you have three test groups, M, V, C. So for each group, assign all  pointers to what you want it to be, without UT_PTR_SET. There is no need to revert them automatically, as long as each test group sets all pointers.

I have some examples here: https://github.com/arstrube/FakeFunctions

But probably James' approach is simpler. Apparently you had the liberty to use function pointers for the target build, which I didn't have, hence the more complicated approach in my case.

**Comment by arstrube** [comment]
> I don't know if I understand you completely here - if you replace every "real" function by a stub and use function pointer to switch between "real" and "mock", how do you handle this for the "real" executable for the target application?

The real executable doesn't know about it at all. Function pointers only exist in the unit test executable.

**Comment by FrankLorenz** [comment]
Thanks for your suggestions. Looks like I I need to rethink some points. Up to now, I just took the structure James Grennings book suggested "as is" without asking myself if I should do something different.
You are right, I can just set all function pointers "by hand" to the mocks because there is no need to re-set them after each test.

So it looks like I do not need a bigger value for SetPointerPlugin::MAX_SET -- from my point of view, you can close the issue if you want.

**Comment by arstrube** [comment]
@basvodde close this?

**Comment by basvodde** [comment]
Not sure yet, so leaving it open for now.
