### ISSUE TITLE
Compiler warning Visual Studio 2005 & 2013 

### ISSUE THREAD

**Issue by BillDenton** [cpputest/cpputest#916]
Compiler warning:
 ... \src\CppUTestExt\IEEE754ExceptionsPlugin.cpp(74) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
This looks similar to https://github.com/cpputest/cpputest/issues/198

**Comment by arstrube** [comment]
Hi there,

Shouldn't this show up in Appveyor when building Head? I see a bunch of other warnings (also interesting, actually) but not this one?

**Comment by arstrube** [comment]
Do you have a better suggestions to fix this than an explicit cast to bool? Would an explicit cast make this warning go away?

**Comment by arstrube** [comment]
It seems the recommended way is 

return (fetestexcept(flag) != 0);

They say that will make the compiler happy.

**Comment by BillDenton** [comment]
It does make the Visual Studio 2013 compiler happy. Not checked if the CppUTest internal tests pass and I don't we are using this in our unit test. So don't know if it is correct.

**Comment by arstrube** [comment]
It is probably the most correct way on the planet to get 'real' bool out of an int return value :)

**Comment by arstrube** [comment]
P.S. There are tests in the test suite that would fail if it wasn't correct. You can check by running the tests with -v -gFE_ to see if they run in VS. I believe they do.

**Comment by arstrube** [comment]
@basvodde the Git installer reset my system config (a nasty habit; it doesn't take the existing one but forces you to make some decisions on the fly and replaces the whole thing, it had autocrlf=true instead of false, but changing that still doesn't restore my previous settings. Which are the correct settings for CppUTest?

**Comment by arstrube** [comment]
It keeps on doing:
```bash
warning: LF will be replaced by CRLF in src/CppUTestExt/IEEE754ExceptionsPlugin.cpp.
```
:-(

**Comment by Andne** [comment]
The .gitattributes file is supposed to override the system setting I think, that's why it got added at one point.  Otherwise, under windows I think I just have the default settings (autocrlf=true I believe) and that seems to work correctly most of the time.

Maybe you just need to force a clean checkout of the files?  Sounds like it's trying to commit without conversion a file that has CRLF but maybe a clean checkout would set the file to LF instead?  Also, git settings are screwy with where they can be overridden, so may need to checkout how many places they've been set when inside the cpputest repository.

**Comment by arstrube** [comment]
Hmm. If I understand the warning correctly, the file should now have CRLF *in the repository*, which is not what we want. Can anyone verify / correct that? If it is just my local problem, I'm not really worried about it.

**Comment by arstrube** [comment]
The compiler warning has been fixed. What about the CRLF issue?
