### ISSUE TITLE
Strange memory leak detector problem.

### ISSUE THREAD

**Issue by kaimast** [cpputest/cpputest#931]
I already posted this in the google group but got no answer. The memory leak detector seems to get stuck in an infinite loop for me.

I have to use this hack to make CppUtest work for me:
https://github.com/kaimast/cpputest/commit/834e0bdb95d67135218455995706aa8222edf379

**Comment by basvodde** [comment]
Hi @kaimast,

I believe me and several others did reply via the googlegroup. Didn't you receive these replies?

I looked at your hacks and the only behavior changing code that you made is a check on whether a node is recursive, as in it has itself as the next. If this were true, then obviously it would go in a recursive look, and you did resolve that. However, that case *should* be impossible.

Now, it is either a bug where this is *somehow* possible, or it is a memory corruption and you resolved the forever loop by the case that will eventually be true.

In order to figure out which one, could you put a breakpoint or so on the break that you inserted and see where it allocates memory and explore the node to see where it was allocated. The node ought to have file/line information in itself, so you ought to print it in a debugger or just printf the content of the node.

Alternatively, could you write a test that exposes this bug, so we can help with debugging this problem? In order words, why to remove production code out of your test and just send the test that causes this problem.

**Comment by arstrube** [comment]
Hi @kaimast - From the information you provide (also on Google Groups), it is impossible to tell what might be going on, as the code of the test and the code being tested are missing.

As @basvodde suggested, perhaps you could write a brief test (all code in the test; no production code) to expose this behavior?

**Comment by uecasm** [comment]
The memory leak tracking could get corrupted like this if the selected platform doesn't have mutex support but the test tries to allocate memory on multiple threads anyway.

**Comment by arstrube** [comment]
@kaimast - are you still there? What is the status of this problem?

**Comment by kaimast** [comment]
Sorry for the delay. I'm still trying to figure out if the project I am using is corrupting memory.

**Comment by basvodde** [comment]
I assume this is resolved ?
