### ISSUE TITLE
FENV Test Failures under Visual Studio 2013/2015

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#954]
Visual Studio 2013 and newer contains the `fenv.h` header file as is able to compile the IEEE754 plugin.  However, something is different in the implementation and a couple of the tests fail.  During a previous pull request, the following were suggested as ways to handle the failure:
- disable the tests alltogether (not a good idea since most pass)
- remove tests that involves invalid (get rid of math.h as well)
- #ifdef the invalid tests away for Msvc

@basvodde Can you please weigh in on which of these you like best?

**Comment by arstrube** [comment]
Thanks @Andne. Although I am not @basvodde, I'd cast my vote for removing tests for FE_INVALID entirely, including the C function that provokes it and math.h, which is only needed for that one function. That will get rid of both failures, and Msvc 2013 can then do valid tests.

I am supporting a large project where they do use the IEEE754 problem (implemented off CppUTest), and we did the same thing there (can't remember why, I think the needed to do a few tests with Msvc). I think in a real-world project, most of the time the output of the function that set FE_INVALID is likely to be input to some other operation, which causes one of the other flags to be set, so it isn't that the error wouldn't get caught. Floating point is Evil :D. That plugin always finds something somewhere ;-).

**Comment by basvodde** [comment]
Removing the tests sounds ok, I guess. I got one failing test on Mac too.

Alternatively, we can leave them as IGNORE_TEST ?

**Comment by arstrube** [comment]
@basvodde which one?

**Comment by arstrube** [comment]
I think IGNORE_TEST wouldn't work, because one test fails indirectly because of the flag not being set, but that test isn't a test to be ignored.

**Comment by arstrube** [comment]
@basvodde - no failure on my Mac (current head, Apple LLVM version 6.1.0)?

**Comment by basvodde** [comment]
I had a failure on Mac on should_not_fail_again_when_test_has_already_failed.

**Comment by arstrube** [comment]
How strange. Are you sure FE_INVALID didn't fail as well? Usually the two fail in concert.

**Comment by arstrube** [comment]
Actually, had a look at should_not_fail_again_when_test_has_already_failed. That test is brittle (apart from the problem with Invalid). I try not to include fenv.h, but that comes at a price -- the hex values is not guaranteed to be the same across platforms. I wonder whether I could rewrite the test to make it more robust.

**Comment by Andne** [comment]
I'm seeing failures in Visual Studio on the same test - should_not_fail_again_when_test_has_already_failed - Visual C++ doesn't like 0x10 for a flag (it's FE_INVALID on that platform).

It looks like the flag checks are to make sure that the floating point flags actually were set to avoid a falsely passing test where the flags weren't set so that's why the count is correct?  That test appears to be the only call to `IEEE754ExceptionsPlugin::checkIeee754ExeptionFlag()`, so is there a reason that it exists beyond supporting that test?  If not I'd say to change the function to provide more what the test is asking for - are any (or maybe it's all) of the flags set?

**Comment by arstrube** [comment]
Hi Andy,

I suspect 0x10 is something else on the Gcc platform, or else the test would have failed somewhere on Travis CI, because I no longer set FE_INVALID.

The original idea of the test was as follows:

1. Cause all flags (that we care about) to be set.
2. Make the test fail in some other way
3. Check that the IEEE plugin doesn't report another failure (after the test already failed).

Later, when `IEEE754ExceptionsPlugin::checkIeee754ExeptionFlag(),` was added, I thought it would be convenient to test that function here and, at the same time, ensure that all flags that should be set indeed are.

Of course, it would be pointless to test a flag that we know we never set, which seems to be happening with VS.

**Comment by arstrube** [comment]
I guess we could reduce this to checking just one flag which works for all platforms?

**Comment by arstrube** [comment]
I'm about to submit a PR where I check that **any** of the three flags are set. This will be much more rubost, it still exercises `IEEE754ExceptionsPlugin::checkIeee754ExeptionFlag()` and it still makes sure the test doesn't pass just because no flags were set in the first place.

**Comment by Andne** [comment]
I guess I'm confused as to what purpose `IEEE754ExceptionsPlugin::checkIeee754ExceptionFlag()` serves.  I wasn't seeing a use for it in the codebase other than in the unit test itself, so it seemed like a function that only existed for the purposes of running a unit test.  In that case maybe it makes more sense to move the "platform-specific" behavior of what the flags to the function and have the function do a slightly different check?  Either that or create a function for each flag that we support (see below) instead of having a function that takes the flag to check.

So the functions would be:
- `IEEE754ExceptionsPlugin::checkOverflowExceptionFlag()`
- `IEEE754ExceptionsPlugin::checkUnderflowExceptionFlag()`
- `IEEE754ExceptionsPlugin::checkInexactExceptionFlag()`

**Comment by arstrube** [comment]
First of all, I think your suggestion is a good one. It would encapsulate the flag stuff in the implementation.

As for its use, it is helpful for debugging: To be able to use this function in the debugger's watch window and see its value change as the problem occurs. This would make your suggestion even more useful, because the debugger also doesn't 'understand' the #defined values from <fenv.h>, or the functions declared therein. By using the functions you suggest, debugging would be made even easier.

**Comment by Andne** [comment]
Sounds good to me, do you want to just modify #960 to do this instead?
